module.exports = {
    AUTHORIZATION: 'Authorization',
    ADMIN: 'admin',
    EMAIL: 'email',
    CONFLICTED_EMAIL: true,
    CAR: 'user',
    CAR_ID: 'car_id',
    ID: '_id',
    PASS: 'password',
    PARAMS: 'params',
    USER: 'user',
    USER_ID: 'user_id',
    V: '__v',
    ROLE: 'role',
};
